import type { PublicForm } from '../types.js';

export interface CodegenOptions {
  baseUrl: string;
  formToken: string;
  outFile: string;
  exportName?: string;
  fetch?: typeof fetch;
}

function toExportName(slug: string): string {
  const camel = slug
    .replace(/[^a-zA-Z0-9]+(.)/g, (_, c: string) => c.toUpperCase())
    .replace(/[^a-zA-Z0-9]/g, '');
  const base = camel.charAt(0).toLowerCase() + camel.slice(1);
  return base.endsWith('Form') ? base : `${base}Form`;
}

function toTypeName(exportName: string): string {
  const pascal = exportName.charAt(0).toUpperCase() + exportName.slice(1);
  return `${pascal}Submit`;
}

function escapeString(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

export function generateFormModule(form: PublicForm, token: string, exportName?: string): {
  code: string;
  exportName: string;
  typeName: string;
} {
  const name = exportName ?? toExportName(form.slug);
  const typeName = toTypeName(name);
  const fieldsJson = JSON.stringify(form.fields, null, 2)
    .split('\n')
    .map((line, i) => (i === 0 ? line : `  ${line}`))
    .join('\n');

  const code = `// Auto-generated by khirby-forms-codegen — do not edit
import type { InferSubmitData } from '@khirby/forms-client';

export const ${name} = {
  token: '${escapeString(token)}',
  name: '${escapeString(form.name)}',
  slug: '${escapeString(form.slug)}',
  kind: '${form.kind}' as const,
  fields: ${fieldsJson} as const,
};

export type ${typeName} = InferSubmitData<typeof ${name}.fields>;
`;

  return { code, exportName: name, typeName };
}

export async function fetchPublicForm(
  baseUrl: string,
  token: string,
  fetchFn: typeof fetch = fetch,
): Promise<PublicForm> {
  const url = `${baseUrl.replace(/\/$/, '')}/api/public/forms/${encodeURIComponent(token)}`;
  const res = await fetchFn(url);
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`Failed to fetch form schema (${res.status}): ${text}`);
  }
  return res.json() as Promise<PublicForm>;
}
